# Common tags applied to all resources
tags:
  cdk-stack: cdk-template
  team: Stanford S. Guillory

name: node-docdb

network:
  vpc:
    natGatewaySubnetName: Public
    maxAzs: 3

  subnets:
    # Backend subnet
    - cidrMask: 21
      name: Private
      subnetType: PRIVATE
    # Data subnet
    - cidrMask: 22
      name: Data
      subnetType: PRIVATE
    # Public subnet
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

compute:
  ecs:
    keyName: stang-linux-us-west-2
    eksOptimizedImage: STANDARD
    version: "1.18"
    nodeGroup:
      name: NodeGroup01
      instanceType: t3.medium
      maxCapacity: 3
      minCapacity: 1
      desiredCapacity: 1
      subnetGroupName: Private
    subnetGroupName: Private
    publicSubnetGroupName: Public
    subnetGroupNames:
      - Private
      - Public

data:
  documentdb:
    domainName: cdk-template
    version: "7.9"
    capacity:
      masterNodes:
        instanceType: m5.large.elasticsearch
        count: 3
      dataNodes:
        instanceType: c5.xlarge.elasticsearch
        count: 3
    ebs:
      volumeSize: 32
    zoneAwareness:
      enabled: true
      count: 3
    subnetGroupName: Data
    logging:
      appLogEnabled: true
      auditLogEnabled: true
      slowIndexLogEnabled: true
      slowIearchLogEnabled: true
